version: "3.8"

services:
  atividade:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ../instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development